### ISSUE TITLE
Header-only version doesn't work with Eigen 3.3.9

### ISSUE THREAD

**Issue by dburov190** [kthohr/optim#36]
Hi,

The header-only version doesn't seem to work with Eigen 3.3.9. `gcc` prints two errors:
```
/home/dburov/.local/include/optimlib/unconstrained/nm.hpp: In function ‘bool optim::internal::nm_impl(optim::Vec_t&, std::function<double(const Eigen::Matrix<double, -1, 1>&, Eigen::Matrix<double, -1, 1>*, void*)>, void*, optim::algo_settings_t*)’:
/home/dburov/.local/include/optimlib/unconstrained/nm.hpp:202:69: error: no match for call to ‘(optim::Vec_t {aka Eigen::Matrix<double, -1, 1>}) (optim::VecInt_t&)’
  202 |         simplex_fn_vals = OPTIM_MATOPS_EVAL(simplex_fn_vals(sort_vec));
```
and
```
/home/dburov/.local/include/optimlib/misc/matrix_ops/access.hpp:35:50: error: ‘all’ is not a member of ‘Eigen’
   35 |     #define OPTIM_MATOPS_ROWS(x, v) (x)(v,Eigen::all) // v is a vector
```

The second error is relatively well-known: `all` is only defined in Eigen's master branch (maybe the latest RC) but not in the latest stable version, which currently is 3.3.9.

The first one is not quite clear to me. It seems like it's trying to convert vector of ints into an int, and fails (output from one of the candidates):
```
include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:178:22: note:   no known conversion for argument 1 from ‘optim::VecInt_t’ {aka ‘Eigen::Matrix<int, -1, 1>’} to ‘Eigen::Index’ {aka ‘long int’}
  178 |     operator()(Index index) const
```

Unrelated, is there any way to NOT use Eigen or Arma? Those are horrible, clumsy, bloated libraries that I try to avoid like the plague. Thanks!

**Comment by djoshuadulle** [comment]
Similar issues in the regular install:

```
In file included from ./include/misc/optim_matdefs.hpp:34, 
                 from ./include/optim.hpp:29, 
                 from src/unconstrained/nm.cpp:25: 
src/unconstrained/nm.cpp: In function ‘bool optim::internal::nm_impl(optim::Vec_t&, std::function<double(const Eigen::Matrix<double, -1, 1>&, Eigen::Matrix<double, -1, 1>*, void*)>, void*, optim::algo_settings_t*)’: 
src/unconstrained/nm.cpp:148:69: error: no match for call to ‘(optim::Vec_t {aka Eigen::Matrix<double, -1, 1>}) (optim::VecInt_t&)’ 
  148 |         simplex_fn_vals = OPTIM_MATOPS_EVAL(simplex_fn_vals(sort_vec));
```
```
In file included from ./include/misc/optim_matdefs.hpp:34,
                 from ./include/optim.hpp:29,
                 from src/unconstrained/nm.cpp:25:
./include/misc/matrix_ops/access.hpp:35:50: error: ‘all’ is not a member of ‘Eigen’
   35 |     #define OPTIM_MATOPS_ROWS(x, v) (x)(v,Eigen::all) // v is a vector
```

For the first error, the stack trace is similar:
```
In file included from /usr/include/eigen3/Eigen/Core:434,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from ./include/misc/optim_options.hpp:107,
                 from ./include/optim.hpp:24,
                 from src/unconstrained/nm.cpp:25:
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:115:41: note: candidate: ‘Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index, Eigen::Index) const [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]’
  115 |     EIGEN_STRONG_INLINE CoeffReturnType operator()(Index row, Index col) const
      |                                         ^~~~~~~~
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:115:41: note:   candidate expects 2 arguments, 1 provided
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:178:5: note: candidate: ‘Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = const double&; Eigen::Index = long int]’
  178 |     operator()(Index index) const
      |     ^~~~~~~~
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:178:22: note:   no known conversion for argument 1 from ‘optim::VecInt_t’ {aka ‘Eigen::Matrix<int, -1, 1>’} to ‘Eigen::Index’ {aka ‘long int’}
  178 |     operator()(Index index) const
```

Looking forward to using this library and any help would be much appreciated.
